apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-idp-conf
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
data:
  config_php: |
    <?php
    $config = array(
      'baseurlpath' => 'simplesaml/',
      'certdir' => 'cert/',
      'loggingdir' => 'log/',
      'datadir' => 'data/',
      'tempdir' => '/tmp/simplesaml',
      'technicalcontact_name' => 'Administrator',
      'technicalcontact_email' => 'na@example.org',
      'timezone' => null,
      'secretsalt' => 'defaultsecretsalt',
      'auth.adminpassword' => '123',
      'admin.protectindexpage' => false,
      'admin.protectmetadata' => false,
      'admin.checkforupdates' => true,
      'trusted.url.domains' => array(),
      'trusted.url.regex' => false,
      'enable.http_post' => false,
      'debug' => array(
        'saml' => false,
        'backtraces' => true,
        'validatexml' => false,
      ),
      'showerrors' => true,
      'errorreporting' => true,
      'logging.level' => SimpleSAML\Logger::NOTICE,
      'logging.handler' => 'syslog',
      'logging.facility' => defined('LOG_LOCAL5') ? constant('LOG_LOCAL5') : LOG_USER,
      'logging.processname' => 'simplesamlphp',
      'logging.logfile' => 'simplesamlphp.log',
      'statistics.out' => array(),
      'proxy' => null,
      'database.dsn' => 'mysql:host=localhost;dbname=saml',
      'database.username' => 'simplesamlphp',
      'database.password' => 'secret',
      'database.options' => array(),
      'database.prefix' => '',
      'database.driver_options' => array(),
      'database.persistent' => false,
      'database.slaves' => array(),
      'enable.saml20-idp' => false,
      'enable.shib13-idp' => false,
      'enable.adfs-idp' => false,
      'enable.wsfed-sp' => false,
      'enable.authmemcookie' => false,
      'default-wsfed-idp' => 'urn:federation:pingfederate:localhost',
      'shib13.signresponse' => true,
      'session.duration' => 8 * (60 * 60), // 8 hours.
      'session.datastore.timeout' => (4 * 60 * 60), // 4 hours
      'session.state.timeout' => (60 * 60), // 1 hour
      'session.cookie.name' => 'SimpleSAMLSessionID',
      'session.cookie.lifetime' => 0,
      'session.cookie.path' => '/',
      'session.cookie.domain' => null,
      'session.cookie.secure' => false,
      'session.phpsession.cookiename' => 'SimpleSAML',
      'session.phpsession.savepath' => null,
      'session.phpsession.httponly' => true,
      'session.authtoken.cookiename' => 'SimpleSAMLAuthToken',
      'session.rememberme.enable' => false,
      'session.rememberme.checked' => false,
      'session.rememberme.lifetime' => (14 * 86400),
      'language' => array(
        'priorities' => array(
          'no' => array('nb', 'nn', 'en', 'se'),
          'nb' => array('no', 'nn', 'en', 'se'),
          'nn' => array('no', 'nb', 'en', 'se'),
          'se' => array('nb', 'no', 'nn', 'en'),
        ),
      ),
      'language.available' => array(
          'en', 'no', 'nn', 'se', 'da', 'de', 'sv', 'fi', 'es', 'ca', 'fr', 'it', 'nl', 'lb',
          'cs', 'sl', 'lt', 'hr', 'hu', 'pl', 'pt', 'pt-br', 'tr', 'ja', 'zh', 'zh-tw', 'ru',
          'et', 'he', 'id', 'sr', 'lv', 'ro', 'eu', 'el', 'af'
      ),
      'language.rtl' => array('ar', 'dv', 'fa', 'ur', 'he'),
      'language.default' => 'en',
      'language.parameter.name' => 'language',
      'language.parameter.setcookie' => true,
      'language.cookie.name' => 'language',
      'language.cookie.domain' => null,
      'language.cookie.path' => '/',
      'language.cookie.secure' => false,
      'language.cookie.httponly' => false,
      'language.cookie.lifetime' => (60 * 60 * 24 * 900),
      'language.i18n.backend' => 'SimpleSAMLphp',
      'attributes.extradictionary' => null,
      'theme.use' => 'default',
      'template.auto_reload' => false,
      'production' => true,
      'idpdisco.enableremember' => true,
      'idpdisco.rememberchecked' => true,
      'idpdisco.validate' => true,
      'idpdisco.extDiscoveryStorage' => null,
      'idpdisco.layout' => 'dropdown',
      'authproc.idp' => array(
        30 => 'core:LanguageAdaptor',
        45 => array(
            'class'         => 'core:StatisticsWithAttribute',
            'attributename' => 'realm',
            'type'          => 'saml20-idp-SSO',
        ),
        50 => 'core:AttributeLimit',
        99 => 'core:LanguageAdaptor',
      ),
      'authproc.sp' => array(
        90 => 'core:LanguageAdaptor',
      ),
      'metadata.sources' => array(
          array('type' => 'flatfile'),
      ),
      'metadata.sign.enable' => false,
      'metadata.sign.privatekey' => null,
      'metadata.sign.privatekey_pass' => null,
      'metadata.sign.certificate' => null,
      'metadata.sign.algorithm' => null,
      'store.type'                    => 'phpsession',
      'store.sql.dsn'                 => 'sqlite:/path/to/sqlitedatabase.sq3',
      'store.sql.username' => null,
      'store.sql.password' => null,
      'store.sql.prefix' => 'SimpleSAMLphp',
    );
    $config['technicalcontact_name'] = "Yevgen Nikitin";
    $config['technicalcontact_email'] = "ynikitin@americanbible.org";
    $config['secretsalt'] = 'kyd79hwzn3i9jhw1gc8mmojmvonfzkz6';
    $config['auth.adminpassword'] = 'l5ief39h1vqpq5w52s6fumyk59j8s5w2'; // @TODO replace it and take from env
    setcookie('NO_CACHE', '1');
    $config['store.type'] = 'sql';
    $config['store.sql.dsn'] = sprintf('mysql:host=%s;port=%s;dbname=%s', '{{ .Values.db.host }}', '3306', '{{ .Values.db.pulse.name }}');
    $config['store.sql.username'] = '{{ .Values.db.pulse.user }}';
    $config['store.sql.password'] = '{{ .Values.db.pulse.pass }}';
    $config['store.sql.prefix'] = 'simplesaml';

  authsources_php: |
    <?php
    $config = array(
      'admin' => array(
          'core:AdminPassword',
      ),
      'abs-sp' => array (
        'saml:SP',
        'entityID' => null,
        'idp' => "{{ .Values.idp.host }}/simplesaml/saml2/idp/metadata.php",
        'discoURL' => null,
      ),
    );

  saml20_sp_hosted_php: |
    <?php
    $host = preg_replace('#^https?://#', '', rtrim('{{ .Values.drupal.url }}','/'))
    $metadata["{{ .Values.drupal.url }}/simplesaml"] = array(
      'saml:SP',
      'host' => $host,
      'privatekey' => 'saml.pem',
      'certificate' => 'saml.crt',
    );

  saml20_idp_remote_php: |
    <?php
    $metadata['{{ .Values.idp.host }}/simplesaml/saml2/idp/metadata.php'] = array (
      'metadata-set' => 'saml20-idp-remote',
      'entityid' => '{{ .Values.idp.host }}/simplesaml/saml2/idp/metadata.php',
      'SingleSignOnService' => 
      array (
        0 => 
        array (
          'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
          'Location' => '{{ .Values.idp.host }}/simplesaml/saml2/idp/SSOService.php',
        ),
      ),
      'SingleLogoutService' => 
      array (
        0 => 
        array (
          'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
          'Location' => '{{ .Values.idp.host }}/simplesaml/saml2/idp/SingleLogoutService.php',
        ),
      ),
      'certData' => 'MIIDRDCCAiwCCQCeGa9BI+xBITANBgkqhkiG9w0BAQsFADBkMQswCQYDVQQGEwJVUzELMAkGA1UECAwCUEExFTATBgNVBAcMDFBoaWxhZGVscGhpYTEMMAoGA1UECgwDQUJTMSMwIQYDVQQDDBpkZXYuc2lnbmV0LmFicy5mdW5zLm5ldC51YTAeFw0xOTAyMjgxNTM2MzJaFw0yOTAyMjcxNTM2MzJaMGQxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJQQTEVMBMGA1UEBwwMUGhpbGFkZWxwaGlhMQwwCgYDVQQKDANBQlMxIzAhBgNVBAMMGmRldi5zaWduZXQuYWJzLmZ1bnMubmV0LnVhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4u83gRaqXcTZ9osCpp4yJHa5QCjXUpfze5iWAwtOcVBUkZt5fW4/86kRmZ3BNWytARILrVXezNp7AH+xNKVSd9A8ShdDzxq3Y9fjpi0Iqo9eH29IMf84S1IxIHvlAlobDSxzs73sNcNpqZVkmh5krOLLK7Ns88FZxw+eYNwMkr+uKpDVzegMarpnYEnQr+DB+wVDXI6SxA8lSbPD76w4c5a5g7bpEJ3WbmIoTzZgZK2kCnrvwALJ710GReHd6bz3G5qP4+rZ8zg9vX9dN272OAtRtvl04ILMlRQxeDHMfpGLrhr+PhZ+lTJ/xLUKas0oKITDB/gogEQhtHsHAJw9zwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQDOk+9vEmbh+3VGPJxE5Ol9tC2nmpizl4lOa8a244zwsvCZooyzbKjd3t7MGm9GCQ2P2G6acILgEeQXc4oasCiysk6CBc7FFFhIEe1tV5djdRW0v/cPSpVBZwhBB/TRS/yTljQpN9yLBBdABhrpdIbrNCiikzcmoEfONzoxwnRrFExcXcKXMoLVtZRG3vKgau07mP8DX3anwl7VN5qYzc94vUZe+PU0vb1EMmItBFCdmj9Eczj3C6WNW0GaQaTLFCREb1sKiMer4EY3UkRoO8gIAudqaYrfAQiWbho6K80/RExNQgQBqHCFJotGCRZ4w7sON+M4Glkp4j3D/l9oM0iG',
      'NameIDFormat' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
      'contacts' => 
      array (
        0 => 
        array (
          'emailAddress' => 'ynikitin@americanbible.org',
          'contactType' => 'technical',
          'givenName' => 'Yevgen',
          'surName' => 'Nikitin',
        ),
      ),
    );