apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-satis-server-conf
  labels:
    {{- include "satis.release_labels" . | nindent 4 }}
data:
  satis_server_conf: |
    PORT=8080
    SSL_PORT=443
    REBUILD_AT=1 0 * * *
    PUSH_SECRET={{ .Values.satis.secret }}
    API_ALLOW=0.0.0.0/0

  satis_json: |
    {
      "name": "ABS composer repo",
      "homepage": "https://gitlab.americanbible.org",
      "repositories": [
          {
              "type": "git",
              "url": "git@gitlab.americanbible.org:ts-eng/abs_contact.git"
          }
      ],
      "require-all":true,
      "require-dependencies":true,
      "require-dev-dependencies":true,
      "minimum-stability":"dev"
    }
