apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-public-files
  labels:
    {{ include "drupal.release_labels" . | indent 4 }}
spec:
  storageClassName: {{ .Values.publicFiles.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.publicFiles.storage }}
---
{{- if .Values.privateFiles.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-private-files
  labels:
    app: {{ .Values.app | quote }}
    release: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.privateFiles.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.privateFiles.storage }}
{{- end }}