apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ssp-conf
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
data:
  config_php: |
    <?php
    $config = array();
  